experimentName: ANNOY Autotune - 1 Million
trialConcurrency: 1
maxExperimentDuration: 2000h
maxTrialDuration: 12h
maxTrialNumber: 100
trainingService:
  platform: local
trialCommand: python3 annoy_experiment.py
trialCodeDirectory: .
tuner:
  name: TPE
  classArgs:
    optimize_mode: maximize
assessor:
  name: Medianstop
  classArgs:
    optimize_mode: maximize
searchSpaceFile: annoy_search_space.json
