experimentName: ANNOY Autotune - 1 Million
trialConcurrency: 1
maxExperimentDuration: 168h
maxTrialDuration: 1h
maxTrialNumber: 1000
trainingService:
  platform: local
trialCommand: python3 annoy_experiment.py
trialCodeDirectory: .
tuner:
  name: GridSearch
  classArgs:
    optimize_mode: maximize
searchSpaceFile: annoy_search_space.json
