experimentName: ANNOY Autotune - 1 Million
trialConcurrency: 1
maxExperimentDuration: 200h
maxTrialDuration: 12h
maxTrialNumber: 20
trainingService:
  platform: local
trialCommand: python3 annoy_experiment.py
trialCodeDirectory: .
tuner:
  name: GridSearch
  classArgs:
    optimize_mode: minimize
searchSpaceFile: annoy_search_space.json
